package co.edu.unbosque.nominabackend.service;

import java.util.concurrent.ThreadLocalRandom;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;

@Service
public class EmailService {

	@Autowired
	private JavaMailSender javaMailSender;

	public void sendWelcomeEmail(String to) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, "utf-8");
		try {
			helper.setTo(to);
			helper.setSubject("Bienvenido a TurboWheels - Portal de Nómina ");

			// Utiliza HTML para dar estilo al correo electrónico
			String htmlMsg = "<!DOCTYPE html>\r\n"
					+ "<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"es-ES\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "	<title></title>\r\n"
					+ "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
					+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><!--[if mso]>\r\n"
					+ "<xml><w:WordDocument xmlns:w=\"urn:schemas-microsoft-com:office:word\"><w:DontUseAdvancedTypographyReadingMail/></w:WordDocument>\r\n"
					+ "<o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml>\r\n"
					+ "<![endif]--><!--[if !mso]><!-->\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;500;600;700;800;900\" rel=\"stylesheet\" type=\"text/css\">\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@100;200;300;400;500;600;700;800;900\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "	<style>\r\n"
					+ "		* {\r\n"
					+ "			box-sizing: border-box;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		body {\r\n"
					+ "			margin: 0;\r\n"
					+ "			padding: 0;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		a[x-apple-data-detectors] {\r\n"
					+ "			color: inherit !important;\r\n"
					+ "			text-decoration: inherit !important;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		#MessageViewBody a {\r\n"
					+ "			color: inherit;\r\n"
					+ "			text-decoration: none;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		p {\r\n"
					+ "			line-height: inherit\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		.desktop_hide,\r\n"
					+ "		.desktop_hide table {\r\n"
					+ "			mso-hide: all;\r\n"
					+ "			display: none;\r\n"
					+ "			max-height: 0px;\r\n"
					+ "			overflow: hidden;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		.image_block img+div {\r\n"
					+ "			display: none;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		sup,\r\n"
					+ "		sub {\r\n"
					+ "			font-size: 75%;\r\n"
					+ "			line-height: 0;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		@media (max-width:550px) {\r\n"
					+ "			.desktop_hide table.icons-inner {\r\n"
					+ "				display: inline-block !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner {\r\n"
					+ "				text-align: center;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner td {\r\n"
					+ "				margin: 0 auto;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				display: none;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-content {\r\n"
					+ "				width: 100% !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.stack .column {\r\n"
					+ "				width: 100%;\r\n"
					+ "				display: block;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				min-height: 0;\r\n"
					+ "				max-height: 0;\r\n"
					+ "				max-width: 0;\r\n"
					+ "				overflow: hidden;\r\n"
					+ "				font-size: 0px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.desktop_hide,\r\n"
					+ "			.desktop_hide table {\r\n"
					+ "				display: table !important;\r\n"
					+ "				max-height: none !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 .block-2.heading_block td.pad {\r\n"
					+ "				padding: 0 0 0 15px !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 .block-2.heading_block h1 {\r\n"
					+ "				font-size: 40px !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 {\r\n"
					+ "				padding: 0 0 5px !important;\r\n"
					+ "			}\r\n"
					+ "		}\r\n"
					+ "	</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]--><!--[if true]><style>.forceBgColor{background-color: white !important}</style><![endif]-->\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body class=\"body forceBgColor\" style=\"background-color: transparent; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
					+ "	<table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: transparent; background-size: auto; background-image: none; background-position: top left; background-repeat: no-repeat;\">\r\n"
					+ "		<tbody>\r\n"
					+ "			<tr>\r\n"
					+ "				<td>\r\n"
					+ "					<table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; background-color: #0a0a0a; border-radius: 30px 30px 0 0; color: #000000; padding: 10px; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-radius: 30px 30px 30px 30px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 153.7px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/821/88y/15i/logo-removebg-preview.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"153.7\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-left:20px;text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #e50914; direction: ltr; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 30px; font-weight: 700; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">¡Bienvenido(a) a TurboWheels!<span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\"></span></span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-3\" style=\"height:20px;line-height:20px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"image_block block-4\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 255px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/6pk/lca/2pq/EntreCol%2B%20Solutions%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"255\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-5\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#dadee1;direction:ltr;font-family:'Lato', Tahoma, Verdana, Segoe, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:center;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0; margin-bottom: 16px;\">¡Has sido registrado exitosamente en nuestro sistema de nómina!</p>\r\n"
					+ "																	<p style=\"margin: 0;\">A partir de ahora, tendrás acceso a toda tu información laboral, contratos, pagos, y beneficios de forma digital y segura.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-6\" style=\"height:60px;line-height:60px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 15px; padding-left: 15px; padding-right: 15px; padding-top: 15px; vertical-align: top;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #e50914; direction: ltr; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 30px; font-weight: 700; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Información Deseada</span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/8ys/ubz/4sy/img2.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: left; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Datos del Empleado</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/mci/sig/2mx/img2%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Contrato</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#101112;direction:ltr;font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:left;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0;\">I'm a new paragraph block.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/j9b/6qj/cu1/img2%20%283%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Valor Pagado de Nómina</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"paragraph_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#dadee1;direction:ltr;font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:center;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0;\">Gracias por ser parte de esta gran familia.<br><strong>¡Arrancamos juntos hacia nuevas metas!</strong></p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-5\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000; border-radius: 0 0 30px 30px; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"50%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 212px;\"><img src=\"https://media4.giphy.com/media/v1.Y2lkPTIwZWI0ZTlkMzdxc216dDE2N2llem8xYnZvM3Z2ejJnb2h1a3d6Yjlud3M1b3ZpbiZlcD12MV9zdGlja2Vyc19zZWFyY2gmY3Q9cw/YNLpTWr725ZLDL8cN7/giphy.gif\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"212\" alt=\"a white car with black background\" title=\"a white car with black background\" height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<div class=\"spacer_block block-2 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-6\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1\" style=\"height:5px;line-height:5px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<div class=\"spacer_block block-2\" style=\"height:10px;line-height:10px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-7\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center; line-height: 0;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\"><!--[if vml]><table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
					+ "																<!--[if !vml]><!-->\r\n"
					+ "																<table class=\"icons-inner\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; padding-left: 0px; padding-right: 0px;\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"><!--<![endif]-->\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Beefree Logo\" src=\"https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png\" height=\"auto\" width=\"34\" align=\"center\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a></td>\r\n"
					+ "																		<td style=\"font-family: 'Inter', sans-serif; font-size: 15px; font-weight: undefined; color: #1e0e4b; vertical-align: middle; letter-spacing: undefined; text-align: center; line-height: normal;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"color: #1e0e4b; text-decoration: none;\">Designed with Beefree</a></td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "				</td>\r\n"
					+ "			</tr>\r\n"
					+ "		</tbody>\r\n"
					+ "	</table><!-- End -->\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			helper.setText(htmlMsg, true); // Indica que el texto es HTML

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}

	public void sendUpdateEmail(String to) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);
		try {
			helper.setTo(to);
			helper.setSubject("Information updated successfully");
			helper.setText("Your information has been updated, if it was not you call the admin");

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
			// Maneja la excepción apropiadamente
		}
	}

	public void sendFileReport(String to, String fileReport) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);
		try {
			helper.setTo(to);
			helper.setText(fileReport);

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}

	public String recoverPasswordEmail(String to) {

		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);

		try {
			helper.setTo(to);
			helper.setSubject("Correct login code");
			String code = randomString();

			String htmlMessage = "<!DOCTYPE html>\r\n"
					+ "<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"es-ES\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "	<title></title>\r\n"
					+ "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
					+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><!--[if mso]>\r\n"
					+ "<xml><w:WordDocument xmlns:w=\"urn:schemas-microsoft-com:office:word\"><w:DontUseAdvancedTypographyReadingMail/></w:WordDocument>\r\n"
					+ "<o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml>\r\n"
					+ "<![endif]--><!--[if !mso]><!-->\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;500;600;700;800;900\" rel=\"stylesheet\" type=\"text/css\">\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@100;200;300;400;500;600;700;800;900\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "	<style>\r\n"
					+ "		* {\r\n"
					+ "			box-sizing: border-box;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		body {\r\n"
					+ "			margin: 0;\r\n"
					+ "			padding: 0;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		a[x-apple-data-detectors] {\r\n"
					+ "			color: inherit !important;\r\n"
					+ "			text-decoration: inherit !important;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		#MessageViewBody a {\r\n"
					+ "			color: inherit;\r\n"
					+ "			text-decoration: none;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		p {\r\n"
					+ "			line-height: inherit\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		.desktop_hide,\r\n"
					+ "		.desktop_hide table {\r\n"
					+ "			mso-hide: all;\r\n"
					+ "			display: none;\r\n"
					+ "			max-height: 0px;\r\n"
					+ "			overflow: hidden;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		.image_block img+div {\r\n"
					+ "			display: none;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		sup,\r\n"
					+ "		sub {\r\n"
					+ "			font-size: 75%;\r\n"
					+ "			line-height: 0;\r\n"
					+ "		}\r\n"
					+ "\r\n"
					+ "		@media (max-width:550px) {\r\n"
					+ "			.desktop_hide table.icons-inner {\r\n"
					+ "				display: inline-block !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner {\r\n"
					+ "				text-align: center;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.icons-inner td {\r\n"
					+ "				margin: 0 auto;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				display: none;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-content {\r\n"
					+ "				width: 100% !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.stack .column {\r\n"
					+ "				width: 100%;\r\n"
					+ "				display: block;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.mobile_hide {\r\n"
					+ "				min-height: 0;\r\n"
					+ "				max-height: 0;\r\n"
					+ "				max-width: 0;\r\n"
					+ "				overflow: hidden;\r\n"
					+ "				font-size: 0px;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.desktop_hide,\r\n"
					+ "			.desktop_hide table {\r\n"
					+ "				display: table !important;\r\n"
					+ "				max-height: none !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 .block-2.heading_block td.pad {\r\n"
					+ "				padding: 0 0 0 15px !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 .block-2.heading_block h1 {\r\n"
					+ "				font-size: 40px !important;\r\n"
					+ "			}\r\n"
					+ "\r\n"
					+ "			.row-1 .column-1 {\r\n"
					+ "				padding: 0 0 5px !important;\r\n"
					+ "			}\r\n"
					+ "		}\r\n"
					+ "	</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]--><!--[if true]><style>.forceBgColor{background-color: white !important}</style><![endif]-->\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body class=\"body forceBgColor\" style=\"background-color: transparent; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
					+ "	<table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: transparent; background-size: auto; background-image: none; background-position: top left; background-repeat: no-repeat;\">\r\n"
					+ "		<tbody>\r\n"
					+ "			<tr>\r\n"
					+ "				<td>\r\n"
					+ "					<table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; background-color: #0a0a0a; border-radius: 30px 30px 0 0; color: #000000; padding: 10px; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-radius: 30px 30px 30px 30px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 153.7px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/821/88y/15i/logo-removebg-preview.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"153.7\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-left:20px;text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #e50914; direction: ltr; font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 30px; font-weight: 700; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">¡Bienvenido(a) a TurboWheels!<span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\"></span></span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-3\" style=\"height:20px;line-height:20px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"image_block block-4\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 255px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/6pk/lca/2pq/EntreCol%2B%20Solutions%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"255\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-5\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#dadee1;direction:ltr;font-family:'Lato', Tahoma, Verdana, Segoe, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:center;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0; margin-bottom: 16px;\">¡Has sido registrado exitosamente en nuestro sistema de nómina!</p>\r\n"
					+ "																	<p style=\"margin: 0;\">A partir de ahora, tendrás acceso a toda tu información laboral, contratos, pagos, y beneficios de forma digital y segura.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-6\" style=\"height:60px;line-height:60px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 15px; padding-left: 15px; padding-right: 15px; padding-top: 15px; vertical-align: top;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #e50914; direction: ltr; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 30px; font-weight: 700; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Información Deseada</span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/8ys/ubz/4sy/img2.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: left; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Datos del Empleado</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/mci/sig/2mx/img2%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Contrato</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#101112;direction:ltr;font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:left;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0;\">I'm a new paragraph block.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"33.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 115px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/j9b/6qj/cu1/img2%20%283%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"115\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<h3 style=\"margin: 0; color: #dadee1; direction: ltr; font-family: 'Lato', Tahoma, Verdana, Segoe, sans-serif; font-size: 16px; font-weight: 400; letter-spacing: normal; line-height: 1.2; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 19px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Valor Pagado de Nómina</span></h3>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"paragraph_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#dadee1;direction:ltr;font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:1.2;text-align:center;mso-line-height-alt:19px;\">\r\n"
					+ "																	<p style=\"margin: 0;\">Gracias por ser parte de esta gran familia.<br><strong>¡Arrancamos juntos hacia nuevas metas!</strong></p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-5\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000; border-radius: 0 0 30px 30px; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"50%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<div style=\"max-width: 212px;\"><img src=\"https://media4.giphy.com/media/v1.Y2lkPTIwZWI0ZTlkMzdxc216dDE2N2llem8xYnZvM3Z2ejJnb2h1a3d6Yjlud3M1b3ZpbiZlcD12MV9zdGlja2Vyc19zZWFyY2gmY3Q9cw/YNLpTWr725ZLDL8cN7/giphy.gif\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"212\" alt=\"a white car with black background\" title=\"a white car with black background\" height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-3\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<div class=\"spacer_block block-2 mobile_hide\" style=\"height:40px;line-height:40px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-6\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top;\">\r\n"
					+ "													<div class=\"spacer_block block-1\" style=\"height:5px;line-height:5px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<div class=\"spacer_block block-2\" style=\"height:10px;line-height:10px;font-size:1px;\">&#8202;</div>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-7\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\">\r\n"
					+ "						<tbody>\r\n"
					+ "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 530px; margin: 0 auto;\" width=\"530\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top;\">\r\n"
					+ "													<table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center; line-height: 0;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\"><!--[if vml]><table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
					+ "																<!--[if !vml]><!-->\r\n"
					+ "																<table class=\"icons-inner\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; padding-left: 0px; padding-right: 0px;\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"><!--<![endif]-->\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Beefree Logo\" src=\"https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png\" height=\"auto\" width=\"34\" align=\"center\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a></td>\r\n"
					+ "																		<td style=\"font-family: 'Inter', sans-serif; font-size: 15px; font-weight: undefined; color: #1e0e4b; vertical-align: middle; letter-spacing: undefined; text-align: center; line-height: normal;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"color: #1e0e4b; text-decoration: none;\">Designed with Beefree</a></td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n"
					+ "								</td>\r\n"
					+ "							</tr>\r\n"
					+ "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "				</td>\r\n"
					+ "			</tr>\r\n"
					+ "		</tbody>\r\n"
					+ "	</table><!-- End -->\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			helper.setText(htmlMessage, true);
			javaMailSender.send(message);
			return code;
		} catch (MessagingException e) {
			e.printStackTrace();
		}
		return "Email not found";

	}

	public int randomNumberInRange(int minimo, int maximo) {

		return ThreadLocalRandom.current().nextInt(minimo, maximo + 1);
	}

	public String randomString() {
		String banco = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
		String cadena = "";
		int longitud = 20;
		for (int x = 0; x < longitud; x++) {
			int indiceAleatorio = randomNumberInRange(0, banco.length() - 1);
			char caracterAleatorio = banco.charAt(indiceAleatorio);
			cadena += caracterAleatorio;
		}
		return cadena;
	}
}
